Feature/k uud hj8 f this apne is not a function
navikt/oppfolgingsplan-old pull request #165
Opened 2021-02-16 10:39 UTC by Vitenok

2021-02-16 11:14 UTC, kaja-nav commented
Åj, dette tror jeg er mine synder fra en annen oppgave :(

2021-02-16 11:20 UTC, kaja-nav requested changes

2021-02-16 11:20 UTC, kaja-nav commented on js/components/oppfolgingsplan/tiltak/liste/Tiltak.js
> +
Jeg tror dette bør løses på en annen måte. Dette henger igjen fra da det var ekspanderbare paneler. Hvis man trykket på "Kommenter" skulle panelet ekspanderes. Siden vi har fjernet ekspanderbare paneler så skal man ikke lenger gjøre det. Jeg tror riktig løsning er å fjerne denne kodesnutten fra `visLagreKommentarSkjema(event)`:
```js
if (!this.state.erApen) {
            this.apne();
}
```

2021-02-16 11:23 UTC, kaja-nav commented
Må gjøre samme i oppfolgingsdialogarbeidsgiver, ser jeg

2021-02-16 11:25 UTC, kaja-nav commented
Også kanskje fikse navnet på pull requesten.

2021-02-16 11:28 UTC, Vitenok commented on js/components/oppfolgingsplan/tiltak/liste/Tiltak.js
> +
Jeg trodde at det gjaldt state til skjema, ikke panelet. Men det du sier ser riktig ut.

2021-02-16 11:35 UTC, Vitenok commented on js/components/oppfolgingsplan/tiltak/liste/Tiltak.js
> +
Pushet update på dette

2021-02-18 09:43 UTC, kaja-nav approved these changes
Ser også bra ut, men husk å fikse navnet så commit message i master blir riktig.

2021-02-18 10:22 UTC, torchr89 approved these changes

2021-02-23 08:52 UTC, merged